### ISSUE TITLE
Rework branch deploy workflow to enable actions/cache

### ISSUE THREAD

**Issue by aaronccasanova** [Shopify/snapit#11]
### Description:

In a recent exploration, I was configuring a GitHub actions/cache to optimize subsequent CI builds and realized our `/snapit` branch deploy workflow is unable to leverage this feature. However, I think there's an opportunity to slightly rework the implementation and bring us even closer to our sub-goal of keeping a majority of work in the GitHub runner.

#### Current branch deploy workflow:
- User comments /snapit
- Snapit runs `changeset version --snapshot snapshot`, and
- Force pushes to another branch for `Buildkite` to take over the build, pack, and upload

#### Proposed branch deploy workflow:
- User comments /snapit
- Snapit runs `changeset version --snapshot snapshot` and the existing `build_script`
- Snapit runs a new `pack_script` command, and
- Force pushes the packed artifacts to another branch for `Buildkite` to upload

This updated workflow could leverage the GitHub/turbo cache to only build the changes between runs, and Buildkite would just be responsible for uploading artifacts. The branch could essentially be a single `.pack` dir that, when pushed to, gets uploaded to Cloudsmith.

**Comment by aaronccasanova** [comment]
Alternatively, we could use a similar pattern to [Changesets action custom publishing](https://github.com/changesets/action?tab=readme-ov-file#custom-publishing):

```yaml
name: Snapit

on:
  issue_comment:
    types:
      - created

jobs:
  snapit:
    name: Snapit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Create snapshot version
        uses: Shopify/snapit@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_script: pnpm turbo run build --cache-dir .turbo
          publish_script: pnpm pack --pack-destination .pack
          branch: snapshot-release
```
